version: '3.12'
services:
  server:
    image: grpc-server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    restart: always
 
  client:
    image: grpc-client
    ports:
      - "8081:8080"
    volumes:
      - ./client:/app
    restart: always
    depends_on:
      - server
