name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  SERVER_IMAGE_NAME: grpc-server
  CLIENT_IMAGE_NAME: grpc-client


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install -r client/requirements.txt
        pip install pytest
    - name: Run tests
      run: |
        pytest -v > pytest_output.txt
      continue-on-error: true
    - name: Display pytest output
      if: always()
      run: cat pytest_output.txt

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      run: |
        docker build -t $DOCKER_HUB_USERNAME/$SERVER_IMAGE_NAME:latest ./server
        docker build -t $DOCKER_HUB_USERNAME/$CLIENT_IMAGE_NAME:latest ./client
        docker push $DOCKER_HUB_USERNAME/$SERVER_IMAGE_NAME:latest
        docker push $DOCKER_HUB_USERNAME/$CLIENT_IMAGE_NAME:latest

  deploy:
      needs: build-and-push
      runs-on: ubuntu-latest
      steps:
      - name: Deploy to server
        env:
          PRIVATE_KEY: ${{ secrets.AWS_SECRET }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker pull ronygeorgen/grpc-server:latest
            docker pull ronygeorgen/grpc-client:latest
          '


